package com.ray.passwordmanager.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table Password.
 */
public class PasswordEntity {

    private Long id;
    /** Not-null value. */
    private String username;
    /** Not-null value. */
    private String password;
    private String category;
    private String note;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PasswordEntity() {
    }

    public PasswordEntity(Long id) {
        this.id = id;
    }

    public PasswordEntity(Long id, String username, String password, String category, String note) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.category = category;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
